FROM node:alpine

MAINTAINER "Andre Luiz Haag" <andreluizhaag@gmail.com>

#ARG proxy_address
#ARG proxy_port
#ARG proxy_user
#ARG proxy_passwd

#RUN npm config set proxy http://$proxy_user:$proxy_passwd@$proxy_address:$proxy_port/
#RUN npm config set https-proxy http://$proxy_user:$proxy_passwd@$proxy_address:$proxy_port/

# Install Gulp & Bower
RUN npm install -g gulp bower

CMD ["node", "-v"]
